version: '2'
services:
    sales-app:
        image: sales
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sales-mysql:3306/sales?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=sales-elasticsearch:9300
        ports:
            - 8080:8080
    sales-mysql:
        extends:
            file: mysql.yml
            service: sales-mysql
    sales-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sales-elasticsearch
